# Auto-generated by scripts/generate-proto.sh — do not edit by hand.
# Source: proto/execution/v1/execution.proto
#
# These stubs are committed to the repo so the project builds without
# requiring a local protoc installation. Regenerate with:
#   bash scripts/generate-proto.sh
