# -*- coding: utf-8 -*-
# Generated by grpcio-tools 1.64.1 from proto/execution/v1/execution.proto
# Run `make proto` to regenerate from source.

import grpc

from . import execution_pb2 as _pb2


class ExecutorServiceStub:
    """Client stub for execution.v1.ExecutorService."""

    def __init__(self, channel: grpc.Channel):
        self.Execute = channel.unary_unary(
            "/execution.v1.ExecutorService/Execute",
            request_serializer=_pb2.ExecuteRequest.SerializeToString,
            response_deserializer=_pb2.ExecuteResponse.FromString,
        )
        self.ExecuteStream = channel.unary_stream(
            "/execution.v1.ExecutorService/ExecuteStream",
            request_serializer=_pb2.ExecuteRequest.SerializeToString,
            response_deserializer=_pb2.StreamChunk.FromString,
        )
        self.Health = channel.unary_unary(
            "/execution.v1.ExecutorService/Health",
            request_serializer=_pb2.HealthRequest.SerializeToString,
            response_deserializer=_pb2.HealthResponse.FromString,
        )
        self.SetStatus = channel.unary_unary(
            "/execution.v1.ExecutorService/SetStatus",
            request_serializer=_pb2.SetStatusRequest.SerializeToString,
            response_deserializer=_pb2.SetStatusResponse.FromString,
        )


class ExecutorServiceServicer:
    """Interface that the executor server must implement.

    grpcio calls these methods with fully-deserialised proto Message objects
    (not raw bytes or dicts). SerializeToString / FromString on the pb2
    message classes handle the binary encoding.
    """

    def Execute(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Execute not implemented")
        raise NotImplementedError

    def ExecuteStream(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("ExecuteStream not implemented")
        raise NotImplementedError

    def Health(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Health not implemented")
        raise NotImplementedError

    def SetStatus(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("SetStatus not implemented")
        raise NotImplementedError


def add_ExecutorServiceServicer_to_server(servicer, server: grpc.Server):
    """Register servicer with a gRPC server.

    Request types are deserialised by grpcio using proto.FromString (binary
    protobuf), matching the Go services' protowire codec exactly.
    """
    from grpc import unary_unary_rpc_method_handler  as _uu
    from grpc import unary_stream_rpc_method_handler as _us

    server.add_generic_rpc_handlers([
        grpc.method_service_handler(
            "execution.v1.ExecutorService",
            {
                "Execute": _uu(
                    servicer.Execute,
                    request_deserializer  = _pb2.ExecuteRequest.FromString,
                    response_serializer   = _pb2.ExecuteResponse.SerializeToString,
                ),
                "ExecuteStream": _us(
                    servicer.ExecuteStream,
                    request_deserializer  = _pb2.ExecuteRequest.FromString,
                    response_serializer   = _pb2.StreamChunk.SerializeToString,
                ),
                "Health": _uu(
                    servicer.Health,
                    request_deserializer  = _pb2.HealthRequest.FromString,
                    response_serializer   = _pb2.HealthResponse.SerializeToString,
                ),
                "SetStatus": _uu(
                    servicer.SetStatus,
                    request_deserializer  = _pb2.SetStatusRequest.FromString,
                    response_serializer   = _pb2.SetStatusResponse.SerializeToString,
                ),
            },
        )
    ])
