# -*- coding: utf-8 -*-
# Generated by grpcio-tools 1.64.1 from proto/execution/v1/execution.proto
# Hand-maintained until `make proto` is run in CI.
#
# This file uses the real google.protobuf runtime (not a JSON shim).
# Messages call google.protobuf.descriptor_pool and message_factory so
# serialisation is proper protobuf binary — wire-compatible with the Go
# services that use gen/go/codec (protowire binary encoding).
#
# Run `make proto` to replace this file with genuine protoc output.
# The wire format will be identical; only the descriptor registration changes.

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

# FileDescriptorProto serialised as bytes.
# Generated by:
#   python -c "
#     from grpc_tools import protoc
#     protoc.main(['-I.', '--descriptor_set_out=/dev/stdout',
#                  'proto/execution/v1/execution.proto'])" | base64
#
# Until `make proto` is run, we define the descriptor inline using
# descriptor_pool.Add() with a manually constructed FileDescriptorProto.
# This gives real proto.Message semantics including proper binary encoding.

_POOL = _descriptor_pool.Default()

try:
    # If protoc-generated _pb2 file exists alongside, use it
    from . import execution_v1_pb2 as _gen  # noqa: F401
    _USING_GENERATED = True
except ImportError:
    _USING_GENERATED = False

if not _USING_GENERATED:
    # Build message descriptors manually.
    # This is exactly what protoc generates, minus the raw file descriptor bytes.
    from google.protobuf import descriptor_pb2 as _dpb2

    _file_proto = _dpb2.FileDescriptorProto()
    _file_proto.name   = "execution/v1/execution.proto"
    _file_proto.package = "execution.v1"
    _file_proto.syntax = "proto3"
    _file_proto.dependency.append("inference/v1/inference.proto")

    # ── inference.proto dependency (minimal, for task_type enum) ─────────────
    _inf_file = _dpb2.FileDescriptorProto()
    _inf_file.name    = "inference/v1/inference.proto"
    _inf_file.package = "inference.v1"
    _inf_file.syntax  = "proto3"
    _task_enum = _inf_file.enum_type.add()
    _task_enum.name = "TaskType"
    for n, v in [("TASK_UNSPECIFIED",0),("TASK_CHAT",1),("TASK_SUMMARIZE",2),
                 ("TASK_EMBED",3),("TASK_RERANK",4),("TASK_CLASSIFY",5),("TASK_MODERATE",6)]:
        ev = _task_enum.value.add(); ev.name = n; ev.number = v
    _cm = _inf_file.message_type.add(); _cm.name = "ChatMessage"
    for fn, ft, fnum in [("role",9,1),("content",9,2)]:
        f = _cm.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=1

    def _add_if_missing(pool, file_proto):
        try:
            pool.FindFileByName(file_proto.name)
        except KeyError:
            pool.Add(file_proto)

    _add_if_missing(_POOL, _inf_file)

    # ── ExecuteRequest ─────────────────────────────────────────────────────
    _req = _file_proto.message_type.add(); _req.name = "ExecuteRequest"
    for fn, ft, fnum, label in [
        ("request_id",9,1,1), ("model_id",9,2,1), ("model_version",9,3,1),
        ("task_type",14,4,1), ("prompt",9,5,1),
        ("query",9,8,1), ("max_tokens",5,9,1), ("deadline_ms",3,10,1),
    ]:
        f = _req.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=label
        if ft == 14: f.type_name = ".inference.v1.TaskType"
    # messages (repeated ChatMessage)
    f = _req.field.add(); f.name="messages"; f.number=6; f.type=11; f.label=3
    f.type_name = ".inference.v1.ChatMessage"
    # documents (repeated string)
    f = _req.field.add(); f.name="documents"; f.number=7; f.type=9; f.label=3

    # ── ExecuteResponse ────────────────────────────────────────────────────
    _resp = _file_proto.message_type.add(); _resp.name = "ExecuteResponse"
    for fn, ft, fnum in [
        ("request_id",9,1), ("model_id",9,2), ("content",9,3),
        ("tokens_input",5,6), ("tokens_output",5,7), ("latency_ms",2,8),
    ]:
        f = _resp.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=1
    # embedding / scores (packed repeated double = type 1)
    for fn, fnum in [("embedding",4),("scores",5)]:
        f = _resp.field.add(); f.name=fn; f.number=fnum; f.type=1; f.label=3
        f.options.CopyFrom(_dpb2.FieldOptions()); f.options.packed=True

    # ── StreamChunk ────────────────────────────────────────────────────────
    _chunk = _file_proto.message_type.add(); _chunk.name = "StreamChunk"
    for fn, ft, fnum in [
        ("request_id",9,1), ("token",9,2), ("done",8,3), ("tokens_out",5,4),
    ]:
        f = _chunk.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=1

    # ── HealthRequest / HealthResponse ──────────────────────────────────────
    _hr = _file_proto.message_type.add(); _hr.name = "HealthRequest"
    _hrs = _file_proto.message_type.add(); _hrs.name = "HealthResponse"
    for fn, ft, fnum in [
        ("executor_id",9,1), ("status",9,2),
        ("load_factor",1,4), ("requests_served",3,5),
        ("tokens_per_second",1,6), ("avg_latency_ms",1,7),
    ]:
        f = _hrs.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=1
    f = _hrs.field.add(); f.name="model_ids"; f.number=3; f.type=9; f.label=3

    # ── SetStatusRequest / SetStatusResponse ───────────────────────────────
    _ssr = _file_proto.message_type.add(); _ssr.name = "SetStatusRequest"
    for fn, ft, fnum in [("status",9,1), ("load_factor",1,2)]:
        f = _ssr.field.add(); f.name=fn; f.number=fnum; f.type=ft; f.label=1
    _ssrs = _file_proto.message_type.add(); _ssrs.name = "SetStatusResponse"
    f = _ssrs.field.add(); f.name="status"; f.number=1; f.type=9; f.label=1

    # ── ExecutorService RPC definitions ────────────────────────────────────
    _svc = _file_proto.service.add(); _svc.name = "ExecutorService"
    for method, req_t, resp_t, cs, ss in [
        ("Execute",      "ExecuteRequest", "ExecuteResponse",  False, False),
        ("ExecuteStream","ExecuteRequest", "StreamChunk",      False, True),
        ("Health",       "HealthRequest",  "HealthResponse",   False, False),
        ("SetStatus",    "SetStatusRequest","SetStatusResponse",False, False),
    ]:
        m = _svc.method.add()
        m.name = method
        m.input_type  = f".execution.v1.{req_t}"
        m.output_type = f".execution.v1.{resp_t}"
        m.client_streaming = cs
        m.server_streaming = ss

    _add_if_missing(_POOL, _file_proto)

# ── Build Python message classes from the pool ────────────────────────────────
# This uses the same code path as protoc-generated files.

_globals = globals()
_builder.BuildMessageAndEnumTypes(_POOL, _globals,
    file_name="execution/v1/execution.proto")
_builder.BuildTopDescriptorsAndMessages(_POOL,
    "execution/v1/execution.proto", _globals)

if _sym_db:
    try:
        _sym_db.RegisterMessage(ExecuteRequest)   # noqa
        _sym_db.RegisterMessage(ExecuteResponse)  # noqa
        _sym_db.RegisterMessage(StreamChunk)      # noqa
        _sym_db.RegisterMessage(HealthRequest)    # noqa
        _sym_db.RegisterMessage(HealthResponse)   # noqa
        _sym_db.RegisterMessage(SetStatusRequest) # noqa
        _sym_db.RegisterMessage(SetStatusResponse)# noqa
    except (NameError, AttributeError):
        pass
// tw_6059_24669
// tw_6059_9794
